-- 1. Create table for Users
CREATE TABLE public.users (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create table for Questions
CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_url text,
  media_type text CHECK (media_type IN ('video', 'image')),
  exam_type text NOT NULL CHECK (exam_type IN ('SIM A', 'SIM C')),
  material_category text NOT NULL CHECK (material_category IN ('Persepsi Bahaya', 'Wawasan', 'Pengetahuan')),
  question_text text NOT NULL,
  options jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create table for Test Results
CREATE TABLE public.test_results (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_email text NOT NULL REFERENCES public.users(email) ON DELETE CASCADE,
  exam_type_taken text NOT NULL CHECK (exam_type_taken IN ('SIM A', 'SIM C')),
  score integer NOT NULL,
  total_questions integer NOT NULL,
  completed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_results ENABLE ROW LEVEL SECURITY;

-- 5. Policies for Users (Public Can Insert, Read Their Own, and Update for Upsert)
-- Users can insert themselves
CREATE POLICY "Allow public insert to users" ON public.users
  FOR INSERT WITH CHECK (true);

-- Users can update (required for upsert operations via email collision)
CREATE POLICY "Allow public update to users" ON public.users
  FOR UPDATE USING (true);

-- Users can select (required to check existence during upsert)
CREATE POLICY "Allow public select to users" ON public.users
  FOR SELECT USING (true);

-- 6. Policies for Questions
-- Everyone (public) can read questions
CREATE POLICY "Allow public read questions" ON public.questions
  FOR SELECT USING (true);

-- Only authenticated Admins can insert/update/delete questions
CREATE POLICY "Allow authenticated insert to questions" ON public.questions
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated update to questions" ON public.questions
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated delete to questions" ON public.questions
  FOR DELETE TO authenticated USING (true);

-- 7. Policies for Test Results
-- Public can insert their own test results
CREATE POLICY "Allow public insert test_results" ON public.test_results
  FOR INSERT WITH CHECK (true);

-- Authenticated admins can read all results
CREATE POLICY "Allow authenticated read test_results" ON public.test_results
  FOR SELECT TO authenticated USING (true);

-- 8. Create table for Feedback
CREATE TABLE public.feedback (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_email text REFERENCES public.users(email) ON DELETE SET NULL,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert to feedback" ON public.feedback
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated read feedback" ON public.feedback
  FOR SELECT TO authenticated USING (true);
